# Generated by Django 5.0.6 on 2024-05-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_chambita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospostulantes',
            name='cv',
            field=models.FileField(upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='datospostulantes',
            name='foto_perfil',
            field=models.ImageField(upload_to='fotos_perfil/'),
        ),
    ]
